<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOyixmuo\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOyixmuo/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOyixmuo.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOyixmuo\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOyixmuo\srcDevDebugProjectContainer([
    'container.build_hash' => 'Oyixmuo',
    'container.build_id' => '3e344832',
    'container.build_time' => 1604230108,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOyixmuo');
